# Generated by Django 6.0.5 on 2026-05-25 05:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_coupon'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='payment_method',
            field=models.CharField(choices=[('COD', 'Cash On Delivery'), ('QR', 'UPI QR'), ('CARD', 'Card Payment')], default='COD', max_length=20),
        ),
    ]
